= Wavemaker Documentation

== Introduction

Wavemaker is designed to be a convenient, cross-platform and full-featured novel writing software solution.
It is and will remain, free and open-source.

It can be installed locally and used offline or accessed via a web interface in any browser on any operating system.

It can sync your work to Google Drive or manuscripts can be exported and imported (allowing you to use any backup option you prefer).

The list below contains links to the various sections of the Wavemaker documentation.
Like Wavemaker itself, there is no _correct_ way to use this documentation.
Read the sections that are relevant to your needs and ignore any that aren't.

* xref:pages/features.adoc[Features]

* xref:pages/accessing.adoc[Accessing]

* xref:pages/getting-started.adoc[Getting started]

* xref:pages/navigation.adoc[Navigation]

* xref:pages/writing-your-manuscript.adoc[Writing your manuscript]

* xref:pages/backup-import-export.adoc[Backup, import and export]

* xref:pages/themes-and-appearance.adoc[Themes and appearance]

* xref:pages/development.adoc[Development]

'''